In [2]:
import pandas as pd
import numpy as np 

In [3]:
tmdb = pd.read_csv("C:/Users/user/Desktop/tmdb_5000_movies.csv")

In [4]:
tmdb.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

In [5]:
tmdb_1 = tmdb[['id', 'title', 'genres', 'vote_average', 'vote_count']]

In [6]:
tmdb_1.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  vote_count  
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           7.2       11800  
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...           6.9        4500  
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.3        4466  
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...           7.6        9106  
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...           6.1        2124

In [7]:
tmdb_1.genres.head()

0    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
1    [{"id": 12, "name": "Adventure"}, {"id": 14, "...
2    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
3    [{"id": 28, "name": "Action"}, {"id": 80, "nam...
4    [{"id": 28, "name": "Action"}, {"id": 12, "nam...
Name: genres, dtype: object

In [8]:
from ast import literal_eval

tmdb_1['genres'] = tmdb_1['genres'].apply(literal_eval)

<ipython-input-8-a943152efe12>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmdb_1['genres'] = tmdb_1['genres'].apply(literal_eval)


In [9]:
tmdb_1.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                              genres  vote_average  vote_count  
0  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...           7.2       11800  
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...           6.9        4500  
2  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...           6.3        4466  
3  [{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...           7.6        9106  
4  [{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...           6.1        2124

In [10]:
tmdb_1['genres'] = tmdb_1['genres'].apply(lambda x:[y['name'] for y in x])
tmdb_1['genres'].head()

<ipython-input-10-0990c9649bde>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmdb_1['genres'] = tmdb_1['genres'].apply(lambda x:[y['name'] for y in x])


0    [Action, Adventure, Fantasy, Science Fiction]
1                     [Adventure, Fantasy, Action]
2                       [Action, Adventure, Crime]
3                 [Action, Crime, Drama, Thriller]
4             [Action, Adventure, Science Fiction]
Name: genres, dtype: object

In [11]:
tmdb_1.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                          genres  vote_average  vote_count  
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800  
1                   [Adventure, Fantasy, Action]           6.9        4500  
2                     [Action, Adventure, Crime]           6.3        4466  
3               [Action, Crime, Drama, Thriller]           7.6        9106  
4           [Action, Adventure, Science Fiction]           6.1        2124

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

tmdb_1['genres_literal'] = tmdb_1['genres'].apply(lambda x:('').join(x))
count_vect = CountVectorizer(min_df = 0, ngram_range=(1,2))
genre_mat = count_vect.fit_transform(tmdb_1['genres_literal'])


<ipython-input-12-dc20a3c16196>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmdb_1['genres_literal'] = tmdb_1['genres'].apply(lambda x:('').join(x))


In [13]:
tmdb_1.head(10)

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   
5     559                              Spider-Man 3   
6   38757                                   Tangled   
7   99861                   Avengers: Age of Ultron   
8     767    Harry Potter and the Half-Blood Prince   
9  209112        Batman v Superman: Dawn of Justice   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   
2                     [Action, Adventure, Crime]           6.3        4466   
3               [Action, Crime, Drama, Thriller]           7.6        9106   
4           [Action, Adventure, Science Fiction]           6.1        2124   
5                   [Fantasy, Action, Adventure]           5.9        3576   
6                            [Animation, Family]           7.4        3330   
7           [Action, Adventure, Science Fiction]           7.3        6767   
8                   [Adventure, Fantasy, Family]           7.4        5293   
9                   [Action, Adventure, Fantasy]           5.7        7004   

                          genres_literal  
0  ActionAdventureFantasyScience Fiction  
1                 AdventureFantasyAction  
2                   ActionAdventureCrime  
3               ActionCrimeDramaThriller  
4         ActionAdventureScience Fiction  
5                 FantasyActionAdventure  
6                        AnimationFamily  
7         ActionAdventureScience Fiction  
8                 AdventureFantasyFamily  
9                 ActionAdventureFantasy

In [14]:
print(genre_mat.shape)

(4803, 1394)


In [15]:
print(genre_mat)

  (0, 77)	1
  (0, 1010)	1
  (0, 78)	1
  (1, 386)	1
  (2, 41)	1
  (3, 160)	1
  (4, 1010)	1
  (4, 93)	1
  (4, 94)	1
  (5, 923)	1
  (6, 473)	1
  (7, 1010)	1
  (7, 93)	1
  (7, 94)	1
  (8, 413)	1
  (9, 73)	1
  (10, 1010)	1
  (10, 393)	1
  (10, 394)	1
  (11, 292)	1
  (12, 386)	1
  (13, 105)	1
  (14, 77)	1
  (14, 1010)	1
  (14, 78)	1
  :	:
  (4783, 1339)	1
  (4784, 761)	1
  (4785, 709)	1
  (4786, 619)	1
  (4787, 1237)	1
  (4787, 1064)	1
  (4787, 1279)	1
  (4788, 1100)	1
  (4789, 709)	1
  (4790, 798)	1
  (4791, 1088)	1
  (4792, 686)	1
  (4793, 709)	1
  (4794, 1340)	1
  (4795, 709)	1
  (4796, 1237)	1
  (4796, 1048)	1
  (4796, 1271)	1
  (4797, 1073)	1
  (4798, 167)	1
  (4799, 619)	1
  (4800, 1145)	1
  (4800, 568)	1
  (4800, 569)	1
  (4802, 698)	1


In [16]:
count_vect.vocabulary_

{'actionadventurefantasyscience': 77,
 'fiction': 1010,
 'actionadventurefantasyscience fiction': 78,
 'adventurefantasyaction': 386,
 'actionadventurecrime': 41,
 'actioncrimedramathriller': 160,
 'actionadventurescience': 93,
 'actionadventurescience fiction': 94,
 'fantasyactionadventure': 923,
 'animationfamily': 473,
 'adventurefantasyfamily': 413,
 'actionadventurefantasy': 73,
 'adventurefantasyactionscience': 393,
 'adventurefantasyactionscience fiction': 394,
 'adventureactionthrillercrime': 292,
 'actionadventurewestern': 105,
 'adventurefamilyfantasy': 372,
 'science': 1237,
 'fictionactionadventure': 1012,
 'science fictionactionadventure': 1240,
 'adventureactionfantasy': 281,
 'actioncomedyscience': 142,
 'actioncomedyscience fiction': 143,
 'actionadventure': 1,
 'adventurefantasy': 385,
 'adventuredramaaction': 346,
 'dramaromancethriller': 853,
 'adventureactionscience': 288,
 'adventureactionscience fiction': 289,
 'thrilleractionadventurescience': 1285,
 'thrilleract

In [17]:
tmdb_1.head()

id                                     title  \
0   19995                                    Avatar   
1     285  Pirates of the Caribbean: At World's End   
2  206647                                   Spectre   
3   49026                     The Dark Knight Rises   
4   49529                               John Carter   

                                          genres  vote_average  vote_count  \
0  [Action, Adventure, Fantasy, Science Fiction]           7.2       11800   
1                   [Adventure, Fantasy, Action]           6.9        4500   
2                     [Action, Adventure, Crime]           6.3        4466   
3               [Action, Crime, Drama, Thriller]           7.6        9106   
4           [Action, Adventure, Science Fiction]           6.1        2124   

                          genres_literal  
0  ActionAdventureFantasyScience Fiction  
1                 AdventureFantasyAction  
2                   ActionAdventureCrime  
3               ActionCrimeDramaThriller  
4         ActionAdventureScience Fiction

In [18]:
# 투표 수 가중평균
m = tmdb_1['vote_count'].quantile(0.6)
c = tmdb_1['vote_average'].mean()

def weight_vote_average(record):
    v = record['vote_count']
    R = record['vote_average']
    
    return ((v/(v+m)) * R) + ((m/(m+v)) * c)

tmdb_1['w_vote'] = tmdb_1.apply(weight_vote_average, axis = 1)

<ipython-input-18-171698592842>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  tmdb_1['w_vote'] = tmdb_1.apply(weight_vote_average, axis = 1)


In [20]:
tmdb_1[['title','w_vote', 'vote_average','vote_count']].sort_values('w_vote', ascending = False)[:10]

title    w_vote  vote_average  vote_count
1881  The Shawshank Redemption  8.396052           8.5        8205
3337             The Godfather  8.263591           8.4        5893
662                 Fight Club  8.216455           8.3        9413
3232              Pulp Fiction  8.207102           8.3        8428
65             The Dark Knight  8.136930           8.2       12002
1818          Schindler's List  8.126069           8.3        4329
3865                  Whiplash  8.123248           8.3        4254
809               Forrest Gump  8.105954           8.2        7927
2294             Spirited Away  8.105867           8.3        3840
2731    The Godfather: Part II  8.079586           8.3        3338

In [23]:
# 코사인 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity

genre_sim = cosine_similarity(genre_mat, genre_mat)
print(genre_sim.shape)

(4803, 4803)


In [24]:
print(genre_sim[:1])

[[1. 0. 0. ... 0. 0. 0.]]


In [25]:
genre_sim_sorted_index = genre_sim.argsort()[:, ::-1]
print(genre_sim_sorted_index[:2])

[[   0  870   46 ... 3172 3173 2401]
 [ 330  129    1 ... 3204 3205    0]]


In [26]:
title_movie = tmdb_1['title'] 
print(title_movie.index)
print(title_movie.index.values)

RangeIndex(start=0, stop=4803, step=1)
[   0    1    2 ... 4800 4801 4802]


In [27]:
def find_sim_movie(tmdb_1, sorted_index, title_name, top_n = 5):
    title_movie = tmdb_1[tmdb_1['title']==title_name]
    title_index = title_movie.index.values
    similar_ind = sorted_index[title_index, : (top_n)]
    print(similar_ind)
    similar_ind = similar_ind.reshape(-1)
    
    return tmdb_1.iloc[similar_ind]
    

In [32]:
similar_movies = find_sim_movie(tmdb_1, genre_sim_sorted_index, 'Iron Man')
similar_movies[['title', 'w_vote']]

[[  51   94 1079   52  101]]


title    w_vote
51                       Pacific Rim  6.656427
94           Guardians of the Galaxy  7.833817
1079                            Dune  6.338041
52    Transformers: Dark of the Moon  6.099210
101               X-Men: First Class  7.032790